# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: mega_power_dev
  host: localhost
  pool: 5
  username: postgres
  password: wasd@123

test:
  adapter: postgresql
  encoding: unicode
  database: mega_power_test
  host: localhost
  pool: 5 
  username: postgres
  password: wasd@123 
